import "server-only";

import { tryParseCalendarDate, type CalendarDate } from "@/lib/domain/hebrew-calendar";

import { defineMutation, notOk, ok, type PerBrideContext, type Result } from "./context";
import { jerusalemTimestampLiteral, parseLocalTime } from "./internal/clock";
import { fail } from "./internal/errors";
import { parseUuid, type Uuid } from "./internal/ids";
import {
  asRow,
  asRows,
  embeddedOne,
  enumField,
  intField,
  optionalStringField,
  uuidField,
} from "./internal/values";

/**
 * Session state changes — done, cancelled, rescheduled. SDD §3.6, §7.5.
 *
 * A cancelled session is never deleted (note b4): it is history and it
 * explains why the course slipped. A reschedule creates a replacement linked
 * by `rescheduled_from_session_id`, which is how the risk aggregate tells
 * "cancelled and rebooked" from "cancelled and forgotten" (§8.1 `high`).
 *
 * None of these recomputes the schedule. Recomputation is a proposal she
 * asks for (`courses.recomputeSchedule`), never a silent write.
 *
 * Every function addresses an existing session by id, scoped to her tenant
 * in the query as well as by RLS, and never creates a row with an id taken
 * from input.
 */

const SESSION_STATUSES = ["planned", "done", "cancelled", "rescheduled"] as const;

async function transition(
  ctx: PerBrideContext,
  operation: string,
  sessionId: string,
  from: "planned",
  to: "done" | "cancelled",
  requireScheduled: boolean,
): Promise<Result<{ sessionId: Uuid }>> {
  const id = parseUuid(sessionId);
  if (!id) return notOk;
  let query = ctx.db
    .from("session")
    .update({ status: to })
    .eq("id", id)
    .eq("tenant_id", ctx.tenantId)
    .eq("status", from)
    .is("deleted_at", null);
  if (requireScheduled) query = query.not("scheduled_at", "is", null);
  const { data, error } = await query.select("id, course!inner(bride_id)");
  if (error) fail(operation, error);
  const rows = asRows(operation, data);
  const row = rows[0];
  if (!row) return notOk;
  ctx.subject(uuidField(operation, embeddedOne(operation, row, "course"), "bride_id"));
  return ok({ sessionId: uuidField(operation, row, "id") });
}

/**
 * A planned, scheduled session becomes `done`. `{ ok: false }` if it is not
 * hers, not planned, or not yet scheduled.
 */
export const markDone = defineMutation(
  { resource: "session", action: "update", subjects: "per-bride" },
  (ctx, sessionId: string) =>
    transition(ctx, "session.mark_done", sessionId, "planned", "done", true),
);

/** A planned session becomes `cancelled`. It stays on the timeline. */
export const cancel = defineMutation(
  { resource: "session", action: "update", subjects: "per-bride" },
  (ctx, sessionId: string) =>
    transition(ctx, "session.cancel", sessionId, "planned", "cancelled", false),
);

export type RescheduleTarget = {
  readonly date: CalendarDate;
  /** Local time of day in Asia/Jerusalem, `HH:MM`. */
  readonly time: string;
} | null;

const RESCHEDULE = "session.reschedule";

/**
 * Moves a planned session, or rebooks a cancelled one.
 *
 * The original keeps its row: a planned original becomes `rescheduled`, a
 * cancelled one stays `cancelled`. A replacement at the same order index
 * carries `rescheduled_from_session_id` and is pinned when given a date — a
 * slot she placed by hand survives recomputation (§7.5). `target = null`
 * rebooks as "טרם נקבע" (not yet scheduled), unpinned.
 *
 * Idempotent on retry: if a replacement already exists, it is updated rather
 * than a second one created. The replacement's id is generated by the
 * database.
 */
export const reschedule = defineMutation(
  { resource: "session", action: "update", subjects: "per-bride" },
  async (
    ctx,
    sessionId: string,
    target: RescheduleTarget,
  ): Promise<Result<{ sessionId: Uuid }>> => {
    const id = parseUuid(sessionId);
    if (!id) return notOk;
    let scheduledAt: string | null = null;
    if (target !== null) {
      const date = tryParseCalendarDate(String(target?.date));
      const time = parseLocalTime(target?.time);
      if (!date || !time) return notOk;
      scheduledAt = jerusalemTimestampLiteral(date, time);
    }

    const { data, error } = await ctx.db
      .from("session")
      .select(
        "id, course_id, order_index, status, location, duration_minutes, course!inner(bride_id, status)",
      )
      .eq("id", id)
      .eq("tenant_id", ctx.tenantId)
      .is("deleted_at", null)
      .maybeSingle();
    if (error) fail(RESCHEDULE, error);
    if (!data) return notOk;
    const original = asRow(RESCHEDULE, data);
    const course = embeddedOne(RESCHEDULE, original, "course");
    const status = enumField(RESCHEDULE, original, "status", SESSION_STATUSES);
    const courseStatus = optionalStringField(RESCHEDULE, course, "status");
    if (status !== "planned" && status !== "cancelled") return notOk;
    if (courseStatus !== "active" && courseStatus !== "draft") return notOk;
    const brideId = uuidField(RESCHEDULE, course, "bride_id");

    const existing = await ctx.db
      .from("session")
      .select("id")
      .eq("rescheduled_from_session_id", id)
      .eq("tenant_id", ctx.tenantId)
      .is("deleted_at", null)
      .limit(1);
    if (existing.error) fail(`${RESCHEDULE}.find_replacement`, existing.error);
    const prior = asRows(RESCHEDULE, existing.data)[0];

    let replacementId: Uuid;
    if (prior) {
      replacementId = uuidField(RESCHEDULE, prior, "id");
      const upd = await ctx.db
        .from("session")
        .update({ scheduled_at: scheduledAt, is_pinned: scheduledAt !== null })
        .eq("id", replacementId)
        .eq("tenant_id", ctx.tenantId)
        .eq("status", "planned");
      if (upd.error) fail(`${RESCHEDULE}.update_replacement`, upd.error);
    } else {
      const ins = await ctx.db
        .from("session")
        .insert({
          tenant_id: ctx.tenantId,
          course_id: uuidField(RESCHEDULE, original, "course_id"),
          order_index: intField(RESCHEDULE, original, "order_index"),
          scheduled_at: scheduledAt,
          duration_minutes: intField(RESCHEDULE, original, "duration_minutes"),
          location: optionalStringField(RESCHEDULE, original, "location"),
          status: "planned",
          is_pinned: scheduledAt !== null,
          rescheduled_from_session_id: id,
        })
        .select("id")
        .single();
      if (ins.error) fail(`${RESCHEDULE}.insert_replacement`, ins.error);
      replacementId = uuidField(RESCHEDULE, asRow(RESCHEDULE, ins.data), "id");
    }

    if (status === "planned") {
      const upd = await ctx.db
        .from("session")
        .update({ status: "rescheduled" })
        .eq("id", id)
        .eq("tenant_id", ctx.tenantId)
        .eq("status", "planned");
      if (upd.error) fail(`${RESCHEDULE}.retire_original`, upd.error);
    }

    ctx.subject(brideId);
    return ok({ sessionId: replacementId });
  },
);
